plugins:
  - jest

env:
  es2021: true,
  node: true

extends:
  - airbnb-base
  - 'plugin:jest/recommended'

parserOptions:
  ecmaVersion: latest
ignorePatterns: ["**/dist/**", "**/public/**"]

import/no-extraneous-dependencies: off

rules:
  import/no-extraneous-dependencies: [error, { devDependencies: true }]
  no-console: 0
  import/extensions:
    - error
    # - ignorePackages
    - js: always
  no-underscore-dangle: [2, { "allow": ["__filename", "__dirname"] }]

