name: Multi-tool CI

on:
  push:
    branches:
      - '**'
    tags:
      - '**'
  pull_request:
    branches:
      - '**'
env:
  CI: true

jobs:
  prepare:
    runs-on: ubuntu-latest
    outputs:
      head_tag: ${{ steps.check.outputs.head_tag }}
      foreign_pr: ${{ steps.check.outputs.foreign_pr }}
  steps:
    - name: Checkout
      uses: actions/checkout@v2.3.4

    - name: Retrieve tags
      run: git fetch --depth=1 origin +refs/tags/*:refs/tags/*

    - name: Set output variables
      id: check
      run: |
        fpr="no"
        tag=""
        if [[ "${{ github.ref }}" == refs/heads/* ]]; then
          tag="$(git tag --points-at HEAD)"
        elif [[ "${{ github.ref }}" == refs/pull/* ]] && [ "${{ github.event.pull_request.head.repo.full_name }}" != "${{ github.event.pull_request.base.repo.full_name }}" ]; then
          fpr="yes"
        fi
        echo "foreign_pr=${fpr}" >> $GITHUB_OUTPUT
        echo "head_tag=${tag}" >> $GITHUB_OUTPUT

  build:
    runs-on: ubuntu-latest
    needs: prepare
    if: "(github.event_name == 'push' && needs.prepare.outputs.head_tag == '') || (github.event_name == 'pull_request' && needs.prepare.outputs.foreign_pr == 'yes')"
    strategy:
      matrix:
        node-version: [ 10.x, 12.x, 14.x, 15.x ]

    steps:
      - uses: actions/checkout@v3
      - name: Используем Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v3
        with:
          node-version: ${{ matrix.node-version }}
          cache: 'npm'
      - name: Запускаем make install
        run: make install
      - name: Прогоним линтер
        run: make lint
      - name : Запустим тесты
        run: make test
      - name: Публикуем coverage
        uses: paambaati/codeclimate-action@v3.0.0
        env:
          CC_TEST_REPORTER_ID: ${{ secrets.CC_TEST_REPORTER_ID }}
        with:
          coverageCommand: make test-coverage
          debug: true
          coverageLocations: |
            ${{github.workspace}}/*.lcov:lcov
